name: Build

on:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

# Declare default permissions as read only
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-kafka-quotas-plugin:
    name: Build Kafka Quotas Plugin
    strategy:
      matrix:
        java:
          - version: "17"
            mainBuild: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@main
        with:
          javaVersion: ${{ matrix.java.version }}

      - name: Install yq
        uses: strimzi/github-actions/.github/actions/dependencies/install-yq@main
        with:
          version: "v4.6.3"

      - name: Build binaries using build-binaries action
        uses: strimzi/github-actions/.github/actions/build/build-binaries@main
        with:
          mainJavaBuild: ${{ matrix.java.mainBuild }}
          artifactSuffix: "kafka-quotas-plugin"
          clusterOperatorBuild: "false"

  deploy-java:
    name: Deploy Java artifacts
    needs:
      - build-kafka-quotas-plugin
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@main
        with:
          javaVersion: "17"

      - name: Install yq
        uses: strimzi/github-actions/.github/actions/dependencies/install-yq@main
        with:
          version: "v4.6.3"

      - name: Deploy to Maven Central
        uses: strimzi/github-actions/.github/actions/build/deploy-java@main
        with:
          modules: "./"
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpgSigningKey: ${{ secrets.GPG_SIGNING_KEY }}
          centralUsername: ${{ secrets.CENTRAL_USERNAME }}
          centralPassword: ${{ secrets.CENTRAL_PASSWORD }}